### ISSUE TITLE
dimnames doesn't work?

### ISSUE THREAD

**Issue by laermbote** [zamorarr/tensorr#12]
Hi Robert,

great package!

however
the following example from your docu runs into an error?
subs <- list(c(1,1,1), c(1,1,2),c(1,2,1),c(1,2,2))
vals <- c(10, 20,30,40)
dims <- c(2,2,2)
x <- sptensor(subs, vals, dims)
dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])
Error in dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2]) :
  'dimnames' applied to non-array

"R version 3.5.0 (2018-04-23)"

thanks Karsten

**Comment by zamorarr** [comment]
Hi Karsten,

Thanks for checking out the package. I am unfortunately not able to reproduce your error when I try running it on my computer. I am using "R version 3.5.2 (2018-12-20)". Are you able to upgrade to this version of R?

Can you tell me what `x` looks like and what it's class is? I just want to make sure that it is in fact an `sptensor`.  It should look like this:

```
> x

<A 2x2x2 sparse tensor with 4 non-zero entries>
subs: <1,1,1> <1,2,1> <1,1,2> <1,2,2>
vals: 10 30 20 40
```

```
> class(x)

[1] "sptensor"
attr(,"package")
[1] "tensorr"
```

**Comment by laermbote** [comment]
Hi Robert,

thanks for your quick answer!

I just upgraded to the last version (64bit).
Same problem.

The trace:
> library(tensorr)
>
> subs <- list(c(1,1,1), c(1,1,2))
> vals <- c(10, 20)
> dims <- c(2,2,2)
> x <- sptensor(subs, vals, dims)
> x
<A 2x2x2 sparse tensor with 2 non-zero entries>
subs: <1,1,1> <1,1,2>
vals: 10 20> dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])
Error in dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2]) :
  'dimnames' applied to non-array
> class(x)
[1] "sptensor"
attr(,"package")
[1] "tensorr"

Maybe a package is missing?

Thanks in advance.

Karsten

Von: Robert Zamora <notifications@github.com>
Gesendet: Sonntag, 30. Dezember 2018 04:33
An: zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com>; Author <author@noreply.github.com>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Hi Karsten,

Thanks for checking out the package. I am unfortunately not able to reproduce your error when I try running it on my computer. I am using "R version 3.5.2 (2018-12-20)". Are you able to upgrade to this version of R?

Can you tell me what x looks like and what it's class is? I just want to make sure that it is in fact an sptensor. It should look like this:

> x



<A 2x2x2 sparse tensor with 4 non-zero entries>

subs: <1,1,1> <1,2,1> <1,1,2> <1,2,2>

vals: 10 30 20 40

> class(x)



[1] "sptensor"

attr(,"package")

[1] "tensorr"

**Comment by laermbote** [comment]
Here we go…..
Actually it a complete fresh set up on 3.5.2. for tensor.

Thanks Karsten

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C
[5] LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] tensorr_0.1.0

loaded via a namespace (and not attached):
[1] assertive.properties_0.0-4 assertive.base_0.0-7       compiler_3.5.2             Matrix_1.2-15              magrittr_1.5
 [6] tools_3.5.2                assertive.types_0.0-3      rpart_4.1-13               codetools_0.2-15           grid_3.5.2
[11] rlang_0.3.0.1              lattice_0.20-38            purrr_0.2.5
> methods(class="sptensor")
[1] [           [<-         as.vector   as_dtensor  as_sptensor Complex     cummax      cummin      cumprod     cumsum      dim
[12] innerprod   length      Math        Math2       nzsubs      nzvals      Ops         outerprod   show        Summary     ttm
[23] ttt         ttv         unfold
see '?methods' for accessing help and source code
> dimnames(x)
NULL





Von: Robert Zamora <notifications@github.com>
Gesendet: Sonntag, 30. Dezember 2018 14:21
An: zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com>; Author <author@noreply.github.com>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Hmmm. Ok let's try a few things.

  1.  What is the result of running sessionInfo()? We'll see if there is any packages missing.
  2.  What does methods(class = "sptensor") return? There should be a function dimnames<-.
  3.  What does dimnames(x) return? Should be a list of NULLs

**Comment by zamorarr** [comment]
Ah ok. It should be returning a list of NULLs.  For example, 

```R
dimnames(x)
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> NULL
```
Are you using the version on CRAN? I believe I added this functionality after I submitted to CRAN but have not updated it there yet. Can you try installing the latest development version from github via:

```R
devtools::install_github("zamorarr/tensorr")
```

**Comment by laermbote** [comment]
Still the same, had to install devtools too.


> library(tensorr)
>
> subs <- list(c(1,1,1), c(1,1,2))
> vals <- c(10, 20)
> dims <- c(2,2,2)
> x <- sptensor(subs, vals, dims)
> x
<A 2x2x2 sparse tensor with 2 non-zero entries>
subs: <1,1,1> <1,1,2>
vals: 10 20> dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])
Error in dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2]) :
  'dimnames' applied to non-array

However, I wish you a  happy to year!
Next year it will work…..

Karsten

Von: Robert Zamora <notifications@github.com>
Gesendet: Montag, 31. Dezember 2018 04:48
An: zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com>; Author <author@noreply.github.com>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Ah ok. It should be returning a list of NULLs. For example,

dimnames(x)

#> [[1]]

#> NULL

#>

#> [[2]]

#> NULL

#>

#> [[3]]

#> NULL

Are you using the version on CRAN? I believe I added this functionality after I submitted to CRAN but have not updated it there yet. Can you try installing the latest development version from github via:

devtools::install_github("zamorarr/tensorr")

**Comment by zamorarr** [comment]
Happy New Year! Ok back at it. Thank you for being patient. Let's get this fixed. I bumped the version number so we can make sure that you're using the most recent version. Can you:

1.) Run `devtools::install_github("zamorarr/tensorr")` again.
2.) Run `library(tensorr)`
3.) Run `devtools::session_info()` and make sure that the version for **tensorr** is 0.1.1?

**Comment by laermbote** [comment]
Hi Robert,

happy new year too.  Thanks for your tenacity.

It isn’t the correct version:

V tensorr              * 0.1.0     2019-01-04 [1] Github (zamorarr/tensorr@169e276)

I have no experience with the devtools. May be you know what’s wrong.

Thanks

Karsten

Von: Robert Zamora <notifications@github.com>
Gesendet: Donnerstag, 3. Januar 2019 02:50
An: zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com>; Author <author@noreply.github.com>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Happy New Year! Ok back at it. Thank you for being patient. Let's get this fixed. I bumped the version number so we can make sure that you're using the most recent version. Can you:

1.) Run devtools::install_github("zamorarr/tensorr") again.
2.) Run library(tensorr)
3.) Run devtools::session_info() and make sure that the version for tensorr is 0.1.1?

**Comment by laermbote** [comment]
Removed package now it s better:


tensorr              * 0.1.1   2019-01-04 [1] Github (zamorarr/tensorr@169e276)

and best of all, dimnames works!

Thanks a lot. I will do some testing. Idea is to use tensorr for simulation on high dimensionality olap.

Karsten
Von: Karsten Oehler <Karsten.Oehler@pmOne.com>
Gesendet: Freitag, 4. Januar 2019 07:31
An: zamorarr/tensorr <reply@reply.github.com>; zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Author <author@noreply.github.com>; Karsten Oehler <Karsten.Oehler@pmOne.com>
Betreff: AW: [zamorarr/tensorr] dimnames doesn't work? (#12)

Hi Robert,

happy new year too.  Thanks for your tenacity.

It isn’t the correct version:

V tensorr              * 0.1.0     2019-01-04 [1] Github (zamorarr/tensorr@169e276)

I have no experience with the devtools. May be you know what’s wrong.

Thanks

Karsten

Von: Robert Zamora <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 3. Januar 2019 02:50
An: zamorarr/tensorr <tensorr@noreply.github.com<mailto:tensorr@noreply.github.com>>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Happy New Year! Ok back at it. Thank you for being patient. Let's get this fixed. I bumped the version number so we can make sure that you're using the most recent version. Can you:

1.) Run devtools::install_github("zamorarr/tensorr") again.
2.) Run library(tensorr)
3.) Run devtools::session_info() and make sure that the version for tensorr is 0.1.1?

**Comment by laermbote** [comment]
Hi Robert,

assigning of names works well, reading from tensor too. But writing?

> library(tensorr)
> subs <- list(c(1,1,1), c(1,1,2),c(1,2,1),c(1,2,2))
> vals <- c(10, 20,30,40)
> dims <- c(2,2,2)
> x <- sptensor(subs, vals, dims)
> dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])
> x['A','a','Jan']
[1] 10
> x['A','a','Jan']=12
Error in x["A", "a", "Jan"] = 12 : object of type 'S4' is not subsettable
>
>
X[1,1,1] is ok.

I am not sure whether it is planned to do so.

Thanks Karsten

Von: Karsten Oehler <Karsten.Oehler@pmOne.com>
Gesendet: Freitag, 4. Januar 2019 07:47
An: zamorarr/tensorr <reply@reply.github.com>; zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Author <author@noreply.github.com>; Karsten Oehler <Karsten.Oehler@pmOne.com>
Betreff: AW: [zamorarr/tensorr] dimnames doesn't work? (#12)

Removed package now it s better:


tensorr              * 0.1.1   2019-01-04 [1] Github (zamorarr/tensorr@169e276)

and best of all, dimnames works!

Thanks a lot. I will do some testing. Idea is to use tensorr for simulation on high dimensionality olap.

Karsten
Von: Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>
Gesendet: Freitag, 4. Januar 2019 07:31
An: zamorarr/tensorr <reply@reply.github.com>; zamorarr/tensorr <tensorr@noreply.github.com<mailto:tensorr@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>
Betreff: AW: [zamorarr/tensorr] dimnames doesn't work? (#12)

Hi Robert,

happy new year too.  Thanks for your tenacity.

It isn’t the correct version:

V tensorr              * 0.1.0     2019-01-04 [1] Github (zamorarr/tensorr@169e276)

I have no experience with the devtools. May be you know what’s wrong.

Thanks

Karsten

Von: Robert Zamora <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 3. Januar 2019 02:50
An: zamorarr/tensorr <tensorr@noreply.github.com<mailto:tensorr@noreply.github.com>>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Happy New Year! Ok back at it. Thank you for being patient. Let's get this fixed. I bumped the version number so we can make sure that you're using the most recent version. Can you:

1.) Run devtools::install_github("zamorarr/tensorr") again.
2.) Run library(tensorr)
3.) Run devtools::session_info() and make sure that the version for tensorr is 0.1.1?

**Comment by zamorarr** [comment]
Hi Karsten,

That functionality was not yet implemented but I just added it. You'll need to re-install the package from my testing branch:

```R
devtools::install_github("zamorarr/tensorr", ref = "replace-by-dimnames")
```

Then try:

```R
library(tensorr) 

# build tensor
subs <- list(c(1,1,1), c(1,1,2),c(1,2,1),c(1,2,2)) 
vals <- c(10, 20,30,40) 
dims <- c(2,2,2) 
x <- sptensor(subs, vals, dims) 

# set dimnames
dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2]) 

# check current value
x['A','a','Jan']

# change value and check
x['A','a','Jan'] <- 12
x['A','a','Jan']
```

Let me know if that works for you!

**Comment by laermbote** [comment]
Hi Robert,

phantastic! I will test it asap. Next I have to deliver a manuscript for my new book but I ‘ll try to do my best.

Thanks a lot

Karsten

Von: Robert Zamora <notifications@github.com>
Gesendet: Montag, 7. Januar 2019 06:36
An: zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com>; Author <author@noreply.github.com>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Hi Karsten,

That functionality was not yet implemented but I just added it. You'll need to re-install the package from my testing branch:

devtools::install_github("zamorarr/tensorr", ref = "replace-by-dimnames")

Then try:

library(tensorr)



# build tensor

subs <- list(c(1,1,1), c(1,1,2),c(1,2,1),c(1,2,2))

vals <- c(10, 20,30,40)

dims <- c(2,2,2)

x <- sptensor(subs, vals, dims)



# set dimnames

dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])



# check current value

x['A','a','Jan']



# change value and check

x['A','a','Jan'] <- 12

x['A','a','Jan']

Let me know if that works for you!

**Comment by laermbote** [comment]
Hi Robert,

I have still the problem. This time with rlang, same situation.
Anything what I can do?

Thanks Karsten

Von: Karsten Oehler
Gesendet: Donnerstag, 10. Januar 2019 04:24
An: zamorarr/tensorr <reply@reply.github.com>; zamorarr/tensorr <tensorr@noreply.github.com>
Cc: Author <author@noreply.github.com>; Karsten Oehler <Karsten.Oehler@pmOne.com>
Betreff: AW: [zamorarr/tensorr] dimnames doesn't work? (#12)

Hi Robert,

I have some problems with installing.
Tibble wasn’t installed before. But even after installing:

devtools::install_github("zamorarr/tensorr", ref = "replace-by-dimnames")
Downloading GitHub repo zamorarr/tensorr@replace-by-dimnames
Installing 1 packages: tibble
Installing package into 'C:/Users/Karsten/AppData/Local/BERT2/lib'
(as 'lib' is unspecified)

  There is a binary version available but the source version is later:
       binary source needs_compilation
tibble  1.4.2  2.0.0              TRUE

  Binaries will be installed
trying URL 'https://ftp.fau.de/cran/bin/windows/contrib/3.5/tibble_1.4.2.zip'
Content type 'application/zip' length 243706 bytes (237 KB)
downloaded 237 KB

package 'tibble' successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package 'tibble'

Remove tibble doesn’t work.

And the problem is the same:

> cube['Produkt11','Nord2','FC2','2016','9','Absatz'] <- 23
Error in cube["Produkt11", "Nord2", "FC2", "2016", "9", "Absatz"] <- 23 :
  object of type 'S4' is not subsettable

Thanks Karsten

Von: Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>
Gesendet: Dienstag, 8. Januar 2019 22:30
An: zamorarr/tensorr <reply@reply.github.com>; zamorarr/tensorr <tensorr@noreply.github.com<mailto:tensorr@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>
Betreff: AW: [zamorarr/tensorr] dimnames doesn't work? (#12)

Hi Robert,

phantastic! I will test it asap. Next I have to deliver a manuscript for my new book but I ‘ll try to do my best.

Thanks a lot

Karsten

Von: Robert Zamora <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Montag, 7. Januar 2019 06:36
An: zamorarr/tensorr <tensorr@noreply.github.com<mailto:tensorr@noreply.github.com>>
Cc: Karsten Oehler <Karsten.Oehler@pmOne.com<mailto:Karsten.Oehler@pmOne.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [zamorarr/tensorr] dimnames doesn't work? (#12)


Hi Karsten,

That functionality was not yet implemented but I just added it. You'll need to re-install the package from my testing branch:

devtools::install_github("zamorarr/tensorr", ref = "replace-by-dimnames")

Then try:

library(tensorr)



# build tensor

subs <- list(c(1,1,1), c(1,1,2),c(1,2,1),c(1,2,2))

vals <- c(10, 20,30,40)

dims <- c(2,2,2)

x <- sptensor(subs, vals, dims)



# set dimnames

dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])



# check current value

x['A','a','Jan']



# change value and check

x['A','a','Jan'] <- 12

x['A','a','Jan']

Let me know if that works for you!

**Comment by zamorarr** [comment]
Hi Karsten,

I unfortunately don't know how to reproduce this error on my system. I don't think it's a problem with this package though, since it has to do with uninstalling other packages. Are you able to use a fresh install of R? The other thing you could try would be to remove some packages manually with `remove.packages("tibble")`

**Comment by zamorarr** [comment]
Great! Thanks for using the package.
