### ISSUE TITLE
mistaken coordinates in the ttm output

### ISSUE THREAD

**Issue by codestatistics** [zamorarr/tensorr#17]
Nice package!

However, when I running ttm on a symmetric tensor, the output does not retain the desired symmetry. Perhaps there is an indexing error in the ttm function? See the example below: 

## create a tensor which satisfies: (1) symmetric in the first two modes, and (2) tensor(,,,1)=tensor(,,,2)
> tensor
<A 2x2x2x2 dense tensor>
, , 1, 1

     [,1] [,2]
[1,] -8.2  1.1
[2,]  1.1 -0.2

, , 2, 1

     [,1] [,2]
[1,] -3.2 -0.2
[2,] -0.2  0.1

, , 1, 2

     [,1] [,2]
[1,] -8.2  1.1
[2,]  1.1 -0.2

, , 2, 2

     [,1] [,2]
[1,] -3.2 -0.2
[2,] -0.2  0.1

## create a matrix A
> A
     [,1] [,2]
[1,] -1.7  2.9
[2,]  0.4  0.0

## However, if we run
ttm(ttm(tensor,A,1),A,2)
<A 2x2x2x2 dense tensor>
, , 1, 1

        [,1]   [,2]
[1,] -36.226  6.852
[2,] -36.226 -6.435

, , 2, 1

       [,1]  [,2]
[1,]  6.852 1.944
[2,] -6.435 6.852

, , 1, 2

      [,1]   [,2]
[1,] 1.944 -1.312
[2,] 6.852  1.944

, , 2, 2

       [,1]   [,2]
[1,] -1.312 -0.512
[2,]  1.944 -0.512

**Comment by zamorarr** [comment]
Hi @codestatistics . You are correct, there is an indexing error when calculating the fiber coordinates. I have a solution and will push the code tomorrow once I add few more tests. Thanks for the catch!
